In [23]:
import torch
import numpy as np
import time
device = 'cuda'if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
randint = torch.randint(-100,100,(6,))
randint


tensor([-42, -11,  51, -74,   3,  81])

In [6]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [8]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
Input = torch.empty(2,3)
Input

tensor([[-5.0887e-29,  2.0207e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [15]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [16]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [17]:
logspace = torch.logspace(start = -10,end= 10, steps = 35)
logspace

tensor([1.0000e-10, 3.8747e-10, 1.5013e-09, 5.8171e-09, 2.2539e-08, 8.7333e-08,
        3.3839e-07, 1.3111e-06, 5.0802e-06, 1.9684e-05, 7.6270e-05, 2.9552e-04,
        1.1450e-03, 4.4367e-03, 1.7191e-02, 6.6608e-02, 2.5809e-01, 1.0000e+00,
        3.8747e+00, 1.5013e+01, 5.8171e+01, 2.2539e+02, 8.7333e+02, 3.3839e+03,
        1.3111e+04, 5.0802e+04, 1.9684e+05, 7.6270e+05, 2.9552e+06, 1.1450e+07,
        4.4367e+07, 1.7191e+08, 6.6608e+08, 2.5809e+09, 1.0000e+10])

In [18]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
a= torch.empty((2,3) , dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
# comparision between computation of cpu and gpu 

In [36]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100).numpy()
np_rand2 = torch.rand(100,100,100,100).numpy()

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()
rand = np.multiply(np_rand1,np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

1.20448518
0.29334164
