In [3]:
import torch
import numpy as np
import time
device = 'cuda'if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [62]:
randint = torch.randint(-100,100,(6,))
randint


tensor([-29,  46,  11,  44,  21, -30])

In [6]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
Input = torch.empty(2,3)
Input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [11]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
logspace = torch.logspace(start = -10,end= 10, steps = 35)
logspace

tensor([1.0000e-10, 3.8747e-10, 1.5013e-09, 5.8171e-09, 2.2539e-08, 8.7333e-08,
        3.3839e-07, 1.3111e-06, 5.0802e-06, 1.9684e-05, 7.6270e-05, 2.9552e-04,
        1.1450e-03, 4.4367e-03, 1.7191e-02, 6.6608e-02, 2.5809e-01, 1.0000e+00,
        3.8747e+00, 1.5013e+01, 5.8171e+01, 2.2539e+02, 8.7333e+02, 3.3839e+03,
        1.3111e+04, 5.0802e+04, 1.9684e+05, 7.6270e+05, 2.9552e+06, 1.1450e+07,
        4.4367e+07, 1.7191e+08, 6.6608e+08, 2.5809e+09, 1.0000e+10])

In [13]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
a= torch.empty((2,3) , dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
# comparision between computation of cpu and gpu 

In [16]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100).numpy()
np_rand2 = torch.rand(100,100,100,100).numpy()

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()
rand = np.multiply(np_rand1,np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.27816439
0.51612401


In [38]:
#torch.stack , torch .multinomial , torhc.tril, torch.triu , input.T / input.transpose . nn.Linear , torch.cat , F.softmax


#DEFINE A PROBABILITY TENSOR
probabilities = torch.tensor([0.1 , 0.9])
#10% chance we get 0 and 90% chance we get 1 each probabaility points to the index of the probability in the tensor
#draw 5 samples from multinomial distribution
samples = torch.multinomial(probabilities , num_samples = 10 , replacement = True)
print(samples)




tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [39]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor , torch.tensor([5])) , dim = 0)
out

#use this when we start generating text given some context  

tensor([1, 2, 3, 4, 5])

In [40]:
out = torch.tril(torch.ones(5,5))  #trill stands for triangle lower 
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [41]:
out = torch.triu(torch.ones(5,5))
out


tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [44]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0 , float('-inf'))
out

#in order to reach the state of tril we exponentiate  

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [45]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [46]:
input = torch.zeros(2,3,4)
out = input.transpose(0 , 2)
out.shape

torch.Size([4, 3, 2])

In [48]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along a new dimension
stacked_tensor= torch.stack([tensor1 , tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias = False)
print(linear(sample))

tensor([-9.6332,  0.7173,  5.1793], grad_fn=<SqueezeBackward4>)


In [53]:
#softmax function chages [a,b,c] to (let sum = exp(a) + exp(b) + exp(c)) [exp((a) / sum , exp(b) / sum , exp(c) / sum] 
import torch.nn.functional as ff

tensor1 = torch.tensor([1.0 , 2.0 , 3.0])

softmax_output = ff.softmax(tensor1,dim = 0) # 0 dim means its a straight line
softmax_output


tensor([0.0900, 0.2447, 0.6652])

In [55]:
#initialisation an embedding vector 
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#create some input indices
input_indices = torch.LongTensor([1,5,3,2])

#apply the embeddinglayer

embedded_output = embedding(input_indices)

#the output will be a tensor of (4 , 100)  where 4 is the number of inputs and 100 is dimensionality of the embedding vector
embedded_output

tensor([[ 0.2666,  0.4444,  0.3515, -0.9552,  0.7707,  0.2342, -1.2816, -0.3714,
          0.8765, -0.0726, -1.2194,  0.4293,  0.9718, -1.1513,  0.0635,  1.2351,
         -1.6537, -2.2976, -1.0188,  0.6041, -1.0365,  0.3992,  0.9816, -0.8485,
          0.3009, -1.2019, -0.5947, -2.0553,  2.0162,  0.0728,  0.4612,  0.6570,
          0.4538, -0.4152,  0.6820,  0.0256, -1.5838, -1.2512,  0.3175, -0.6192,
         -1.8162,  2.4363,  0.2941, -0.6250,  0.5987, -0.4482, -0.4199,  0.4196,
         -1.3031, -0.0159, -0.0502, -0.0746,  0.7873, -0.6074,  0.4227, -0.6482,
         -0.0631,  0.8111, -0.8053,  0.2129, -2.0971, -0.2417, -0.5072, -1.3366,
         -0.0987, -0.5102,  4.0755,  0.6364, -0.1660, -2.6565, -1.3824,  0.8614,
         -0.8145,  1.2422, -0.0753,  1.3404,  0.6206, -2.1499, -0.3436, -1.0764,
         -0.5196,  0.4692,  0.0823, -0.5842, -0.5659, -1.2861, -1.7784, -0.6802,
          0.6927, -1.3859,  1.3855,  0.3572, -0.5716,  0.5842,  0.4747, -2.2647,
          0.1904, -2.2185, -

In [60]:
int_64 = torch.randint(1,(3,2)).float()  #typecasted integer to float important for matrix multiplication in our model
float_32 = torch.rand(2,3)
result = torch.matmul(int_64,float_32)
result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])